name: klipper

x-klipper-svc: &klipper-svc
  image: mkuf/klipper:latest
  restart: unless-stopped
  privileged: true
  volumes:
    - /dev:/dev
    - ./config:/opt/printer_data/config
    - run:/opt/printer_data/run
    - /home/pi/gcode:/opt/printer_data/gcodes
    - log:/opt/printer_data/logs

x-moonraker-svc: &moonraker-svc
  image: mkuf/moonraker:latest
  restart: unless-stopped
  volumes:
    - /dev/null:/opt/klipper/config/null
    - /dev/null:/opt/klipper/docs/null
    - ./config:/opt/printer_data/config
    - ./config/moonraker.secrets:/opt/printer_data/moonraker.secrets
    - run:/opt/printer_data/run
    - /home/pi/gcode:/opt/printer_data/gcodes
    - log:/opt/printer_data/logs

x-ustreamer-svc: &ustreamer-svc
  image: mkuf/ustreamer:latest
  restart: unless-stopped

## Service Definitions
services:
  slowboi-klipper:
    <<: *klipper-svc
    command: -I printer_data/run/slowboi.klipper.tty -a printer_data/run/slowboi.klipper.sock printer_data/config/slowboi/printer.cfg -l printer_data/logs/slowboi.klippy.log
    labels:
      org.prind.service: klipper
      org.prind.printer: slowboi
    profiles:
      - garage

  slowboi-moonraker:
    <<: *moonraker-svc
    command: -d printer_data -c printer_data/config/slowboi/moonraker.conf -l printer_data/logs/slowboi.moonraker.log
    ports:
      - 8101:7125
    labels:
      org.prind.service: moonraker
      org.prind.printer: slowboi
    profiles:
      - garage

  slowboi-webcam:
    <<: *ustreamer-svc
    command: --host=0.0.0.0 --port=8080 --slowdown --device=/dev/webcam --resolution=640x480 --format=YUYV --desired-fps=30
    devices:
      - /dev/v4l/by-id/usb-Generic_USB2.0_PC_CAMERA-video-index0:/dev/webcam
    labels:
      org.prind.service: webcam
      org.prind.printer: slowboi
    profiles:
      - garage

  hugeboi-klipper:
    <<: *klipper-svc
    command: -I printer_data/run/hugeboi.klipper.tty -a printer_data/run/hugeboi.klipper.sock printer_data/config/hugeboi/printer.cfg -l printer_data/logs/hugeboi.klippy.log
    labels:
      org.prind.service: klipper
      org.prind.printer: hugeboi
    profiles:
      - garage

  hugeboi-moonraker:
    <<: *moonraker-svc
    command: -d printer_data -c printer_data/config/hugeboi/moonraker.conf -l printer_data/logs/hugeboi.moonraker.log
    ports:
      - 8201:7125
    labels:
      org.prind.service: moonraker
      org.prind.printer: hugeboi
    profiles:
      - garage

  hugeboi-webcam:
    <<: *ustreamer-svc
    command: --host=0.0.0.0 --port=8080 --slowdown --device=/dev/webcam --resolution=1920x1080 --format=MJPEG --desired-fps=30
    devices:
      - /dev/video19:/dev/webcam
    labels:
      org.prind.service: webcam
      org.prind.printer: hugeboi
    profiles:
      - garage

  smolboi-klipper:
    image: mkuf/klipper:latest
    restart: unless-stopped
    privileged: true
    logging:
      driver: none
    command: -I printer_data/run/smolboi.klipper.tty -a printer_data/run/smolboi.klipper.sock printer_data/config/smolboi/printer.cfg -l printer_data/logs/smolboi.klippy.log
    volumes:
      - /dev:/dev
      - ./config:/opt/printer_data/config
      - run:/opt/printer_data/run
      - /home/pi/gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
    labels:
      org.prind.service: klipper
      org.prind.printer: smolboi
    profiles:
      - office

  smolboi-moonraker:
    image: mkuf/moonraker:latest
    restart: unless-stopped
    pid: host
    command: -d printer_data -c printer_data/config/smolboi/moonraker.conf -l printer_data/logs/smolboi.moonraker.log
    logging:
      driver: none
    depends_on:
      smolboi-klipper:
        condition: service_started
    ports:
      - 8101:7125
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - run:/opt/printer_data/run
      - /home/pi/gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
      - moonraker-db:/opt/printer_data/database
      - ./config:/opt/printer_data/config
    labels:
      org.prind.service: moonraker
      org.prind.printer: smolboi
    profiles:
      - office

volumes:
  run:
  moonraker-db:
  log:
